from PyQt5 import QtWidgets, QtCore, QtGui

class debtItm(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(10, 10, 1201, 251))
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1181, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.nameLab = QtWidgets.QLabel(self.frame)
        self.nameLab.setGeometry(QtCore.QRect(10, 60, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.nameLab.setFont(font)
        self.nameLab.setTextFormat(QtCore.Qt.AutoText)
        self.nameLab.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLab.setObjectName("nameLab")
        self.nameLab.setText("Capital One")
        self.totalDue = QtWidgets.QLabel(self.frame)
        self.totalDue.setGeometry(QtCore.QRect(150, 10, 121, 101))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.totalDue.setFont(font)
        self.totalDue.setObjectName("totalDue")
        self.totalDue.setText("Total Due: ")
        self.monthlyDue = QtWidgets.QLabel(self.frame)
        self.monthlyDue.setGeometry(QtCore.QRect(150, 110, 121, 101))
        self.monthlyDue.setFont(font)
        self.monthlyDue.setObjectName("MonthlyDue")
        self.monthlyDue.setText("Due Monthly: ")
        self.valueDue = QtWidgets.QLabel(self.frame)
        self.valueDue.setGeometry(QtCore.QRect(220, 10, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.valueDue.setFont(font)
        self.valueDue.setAlignment(QtCore.Qt.AlignCenter)
        self.valueDue.setObjectName("valueDue")
        self.valueDue.setText("2451.65")
        self.monthlyValueDue = QtWidgets.QLabel(self.frame)
        self.monthlyValueDue.setGeometry(QtCore.QRect(220, 110, 201, 101))
        self.monthlyValueDue.setFont(font)
        self.monthlyValueDue.setAlignment(QtCore.Qt.AlignCenter)
        self.monthlyValueDue.setObjectName("monthlyValueDue")
        self.monthlyValueDue.setText("2451.65")
        self.InterestLab = QtWidgets.QLabel(self.frame)
        self.InterestLab.setGeometry(QtCore.QRect(410, 50, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.InterestLab.setFont(font)
        self.InterestLab.setAlignment(QtCore.Qt.AlignCenter)
        self.InterestLab.setObjectName("InterestLab")
        self.InterestLab.setText("Interest: ")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(410, 120, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_5.setText("Date Due: ")
        self.Percentage = QtWidgets.QLabel(self.frame)
        self.Percentage.setGeometry(QtCore.QRect(480, 40, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.Percentage.setFont(font)
        self.Percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.Percentage.setObjectName("Percentage")
        self.Percentage.setText("25%")
        self.Date = QtWidgets.QLabel(self.frame)
        self.Date.setGeometry(QtCore.QRect(502, 110, 120, 71))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.Date.setFont(font)
        self.Date.setAlignment(QtCore.Qt.AlignCenter)
        self.Date.setObjectName("Date")
        self.Date.setText("5/15/23")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget.setGeometry(QtCore.QRect(635, 10, 391, 211))
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(1032, 10, 141, 107))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Hacer un Pago")
        self.pushButton2 = QtWidgets.QPushButton(self.frame)
        self.pushButton2.setGeometry(QtCore.QRect(1032, 115, 141, 107))
        self.pushButton2.setObjectName("pushButton")
        self.pushButton2.setText("Borrar?")
        self.pushButton3 = QtWidgets.QPushButton(self.frame)
        self.pushButton3.setGeometry(QtCore.QRect(10, 160, 60, 60))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton3.setText("Pagos")
        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(self.widget)